name: Suresh to All World Shops Auto-deploy

on:
  push:
    branches:
      - main  # If your main branch is called 'master', change 'main' to 'master'

jobs:
  sync-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SURESH_TO_AWS_GITHUB_AUTO_DEPLOY }}
          known_hosts: ${{ secrets.SURESH_TO_AWS_GITHUB_AUTO_DEPLOY }} # This auto-scans github.com for you

      - name: Push Changes to Account B
        run: |
          git remote add target git@github.com:AllWorldShops/bom-converter.git
          
          git push target refs/heads/*:refs/heads/* --force
          git push target refs/tags/*:refs/tags/* --force
